In [1]:
pip install pandas numpy jupyterlab scikit-learn torch

Requirement already satisfied: pandas in ./.venv/lib/python3.11/site-packages (2.3.2)
Requirement already satisfied: numpy in ./.venv/lib/python3.11/site-packages (2.3.3)
Requirement already satisfied: jupyterlab in ./.venv/lib/python3.11/site-packages (4.4.9)
Requirement already satisfied: scikit-learn in ./.venv/lib/python3.11/site-packages (1.7.2)
Requirement already satisfied: torch in ./.venv/lib/python3.11/site-packages (2.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: async-lru>=1.0.0 in ./.venv/lib/python3.11/site-packages (from jupyterlab) (2.0.5)
Requirement already satisfied: httpx<1,>=0.25.0 in ./.venv/lib/python3.11/site-packages (from jupyterlab) (0.28.1)
Requirement already satisfied: ipykernel!=6.30.0,>=6.5.0 in ./.venv/lib/python3.11/site-packages (from jupyterlab) (6.30.1)
Requirement already satisfied: jinja2>=3.0.3 in ./.venv/lib/python3.11/site-packages (from jupyterlab) (3.1.6)
Requirement already satisfied: jupyter-core in ./.venv/lib/python3.11/site-packages (from jupyterlab) (5.8.1)
Requirement already satisfied: jupyter-lsp>=2.0.0 in ./.venv/lib/python3.11/site-packages (from jupyterlab) (2.3.0)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in ./.venv/lib/python3.11/site-packages (from jupyterlab) (2.17.0)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in ./.venv/lib/python3.11/site-packages (from jupyterlab) (2.27.3)
Requirement already satisfied: notebook-shim>=0.2 in ./.venv/lib/python3.11/site-packages (from jupyterlab) (0.2.4)
Requirement already satisfied: packaging in ./.venv/lib/python3.11/site-packages (from jupyterlab) (25.0)
Requirement already satisfied: setuptools>=41.1.0 in ./.venv/lib/python3.11/site-packages (from jupyterlab) (66.1.1)
Requirement already satisfied: tornado>=6.2.0 in ./.venv/lib/python3.11/site-packages (from jupyterlab) (6.5.2)
Requirement already satisfied: traitlets in ./.venv/lib/python3.11/site-packages (from jupyterlab) (5.14.3)
Requirement already satisfied: scipy>=1.8.0 in ./.venv/lib/python3.11/site-packages (from scikit-learn) (1.16.2)
Requirement already satisfied: joblib>=1.2.0 in ./.venv/lib/python3.11/site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in ./.venv/lib/python3.11/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: filelock in ./.venv/lib/python3.11/site-packages (from torch) (3.19.1)
Requirement already satisfied: typing-extensions>=4.10.0 in ./.venv/lib/python3.11/site-packages (from torch) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in ./.venv/lib/python3.11/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx in ./.venv/lib/python3.11/site-packages (from torch) (3.5)
Requirement already satisfied: fsspec in ./.venv/lib/python3.11/site-packages (from torch) (2025.9.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in ./.venv/lib/python3.11/site-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in ./.venv/lib/python3.11/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in ./.venv/lib/python3.11/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in ./.venv/lib/python3.11/site-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in ./.venv/lib/python3.11/site-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in ./.venv/lib/python3.11/site-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in ./.venv/lib/python3.11/site-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in ./.venv/lib/python3.11/site-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in ./.venv/lib/python3.11/site-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in ./.venv/lib/python3.11/site-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in ./.venv/lib/python3.11/site-packages (from torch) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in ./.venv/lib/python3.11/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in ./.venv/lib/python3.11/site-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in ./.venv/lib/python3.11/site-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.4.0 in ./.venv/lib/python3.11/site-packages (from torch) (3.4.0)
Requirement already satisfied: anyio in ./.venv/lib/python3.11/site-packages (from httpx<1,>=0.25.0->jupyterlab) (4.11.0)
Requirement already satisfied: certifi in ./.venv/lib/python3.11/site-packages (from httpx<1,>=0.25.0->jupyterlab) (2025.8.3)
Requirement already satisfied: httpcore==1.* in ./.venv/lib/python3.11/site-packages (from httpx<1,>=0.25.0->jupyterlab) (1.0.9)
Requirement already satisfied: idna in ./.venv/lib/python3.11/site-packages (from httpx<1,>=0.25.0->jupyterlab) (3.10)
Requirement already satisfied: h11>=0.16 in ./.venv/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab) (0.16.0)
Requirement already satisfied: comm>=0.1.1 in ./.venv/lib/python3.11/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in ./.venv/lib/python3.11/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (1.8.17)
Requirement already satisfied: ipython>=7.23.1 in ./.venv/lib/python3.11/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (9.5.0)
Requirement already satisfied: jupyter-client>=8.0.0 in ./.venv/lib/python3.11/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (8.6.3)
Requirement already satisfied: matplotlib-inline>=0.1 in ./.venv/lib/python3.11/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.1.7)
Requirement already satisfied: nest-asyncio>=1.4 in ./.venv/lib/python3.11/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (1.6.0)
Requirement already satisfied: psutil>=5.7 in ./.venv/lib/python3.11/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (7.1.0)
Requirement already satisfied: pyzmq>=25 in ./.venv/lib/python3.11/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (27.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.11/site-packages (from jinja2>=3.0.3->jupyterlab) (3.0.2)
Requirement already satisfied: platformdirs>=2.5 in ./.venv/lib/python3.11/site-packages (from jupyter-core->jupyterlab) (4.4.0)
Requirement already satisfied: argon2-cffi>=21.1 in ./.venv/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (25.1.0)
Requirement already satisfied: jupyter-events>=0.11.0 in ./.venv/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in ./.venv/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.5.3)
Requirement already satisfied: nbconvert>=6.4.4 in ./.venv/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (7.16.6)
Requirement already satisfied: nbformat>=5.3.0 in ./.venv/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (5.10.4)
Requirement already satisfied: overrides>=5.0 in ./.venv/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in ./.venv/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.23.1)
Requirement already satisfied: send2trash>=1.8.2 in ./.venv/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in ./.venv/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in ./.venv/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (1.8.0)
Requirement already satisfied: babel>=2.10 in ./.venv/lib/python3.11/site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab) (2.17.0)
Requirement already satisfied: json5>=0.9.0 in ./.venv/lib/python3.11/site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab) (0.12.1)
Requirement already satisfied: jsonschema>=4.18.0 in ./.venv/lib/python3.11/site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab) (4.25.1)
Requirement already satisfied: requests>=2.31 in ./.venv/lib/python3.11/site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab) (2.32.5)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./.venv/lib/python3.11/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in ./.venv/lib/python3.11/site-packages (from anyio->httpx<1,>=0.25.0->jupyterlab) (1.3.1)
Requirement already satisfied: argon2-cffi-bindings in ./.venv/lib/python3.11/site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab) (25.1.0)
Requirement already satisfied: decorator in ./.venv/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in ./.venv/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (1.1.1)
Requirement already satisfied: jedi>=0.16 in ./.venv/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.19.2)
Requirement already satisfied: pexpect>4.3 in ./.venv/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in ./.venv/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in ./.venv/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (2.19.2)
Requirement already satisfied: stack_data in ./.venv/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.6.3)
Requirement already satisfied: attrs>=22.2.0 in ./.venv/lib/python3.11/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in ./.venv/lib/python3.11/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in ./.venv/lib/python3.11/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in ./.venv/lib/python3.11/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (0.27.1)
Requirement already satisfied: python-json-logger>=2.0.4 in ./.venv/lib/python3.11/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (3.3.0)
Requirement already satisfied: pyyaml>=5.3 in ./.venv/lib/python3.11/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (6.0.3)
Requirement already satisfied: rfc3339-validator in ./.venv/lib/python3.11/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in ./.venv/lib/python3.11/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (0.1.1)
Requirement already satisfied: beautifulsoup4 in ./.venv/lib/python3.11/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (4.13.5)
Requirement already satisfied: bleach[css]!=5.0.0 in ./.venv/lib/python3.11/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (6.2.0)
Requirement already satisfied: defusedxml in ./.venv/lib/python3.11/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in ./.venv/lib/python3.11/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in ./.venv/lib/python3.11/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (3.1.4)
Requirement already satisfied: nbclient>=0.5.0 in ./.venv/lib/python3.11/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.10.2)
Requirement already satisfied: pandocfilters>=1.4.1 in ./.venv/lib/python3.11/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (1.5.1)
Requirement already satisfied: fastjsonschema>=2.15 in ./.venv/lib/python3.11/site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab) (2.21.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.11/site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.11/site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab) (2.5.0)
Requirement already satisfied: ptyprocess in ./.venv/lib/python3.11/site-packages (from terminado>=0.8.3->jupyter-server<3,>=2.4.0->jupyterlab) (0.7.0)
Requirement already satisfied: webencodings in ./.venv/lib/python3.11/site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in ./.venv/lib/python3.11/site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (1.4.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in ./.venv/lib/python3.11/site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.8.5)
Requirement already satisfied: fqdn in ./.venv/lib/python3.11/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (1.5.1)
Requirement already satisfied: isoduration in ./.venv/lib/python3.11/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in ./.venv/lib/python3.11/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (3.0.0)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in ./.venv/lib/python3.11/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (1.1.0)
Requirement already satisfied: uri-template in ./.venv/lib/python3.11/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in ./.venv/lib/python3.11/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (24.11.1)
Requirement already satisfied: wcwidth in ./.venv/lib/python3.11/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.2.14)
Requirement already satisfied: cffi>=1.0.1 in ./.venv/lib/python3.11/site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab) (2.0.0)
Requirement already satisfied: soupsieve>1.2 in ./.venv/lib/python3.11/site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (2.8)
Requirement already satisfied: executing>=1.2.0 in ./.venv/lib/python3.11/site-packages (from stack_data->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in ./.venv/lib/python3.11/site-packages (from stack_data->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (3.0.0)
Requirement already satisfied: pure-eval in ./.venv/lib/python3.11/site-packages (from stack_data->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.2.3)
Requirement already satisfied: pycparser in ./.venv/lib/python3.11/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab) (2.23)
Requirement already satisfied: lark>=1.2.2 in ./.venv/lib/python3.11/site-packages (from rfc3987-syntax>=1.1.0->jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (1.3.0)
Requirement already satisfied: arrow>=0.15.0 in ./.venv/lib/python3.11/site-packages (from isoduration->jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (1.3.0)
Requirement already satisfied: types-python-dateutil>=2.8.10 in ./.venv/lib/python3.11/site-packages (from arrow>=0.15.0->isoduration->jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab) (2.9.0.20250822)
Note: you may need to restart the kernel to use updated packages.

In [23]:
import pandas as pd
train=pd.read_csv('./dataset/train.csv')
test=pd.read_csv('./dataset/test.csv')

# Dropping id from test dataset
id_test = test['id']
x_test = test.drop(['id'], axis=1, inplace=True)

train.head()

,id,RhythmScore,AudioLoudness,VocalContent,AcousticQuality,InstrumentalScore,LivePerformanceLikelihood,MoodScore,TrackDurationMs,Energy,BeatsPerMinute
0,0,0.603610,-7.636942,0.023500,0.000005,0.000001,0.051385,0.409866,290715.6450,0.826267,147.53020
1,1,0.639451,-16.267598,0.071520,0.444929,0.349414,0.170522,0.651010,164519.5174,0.145400,136.15963
2,2,0.514538,-15.953575,0.110715,0.173699,0.453814,0.029576,0.423865,174495.5667,0.624667,55.31989
3,3,0.734463,-1.357000,0.052965,0.001651,0.159717,0.086366,0.278745,225567.4651,0.487467,147.91212
4,4,0.532968,-13.056437,0.023500,0.068687,0.000001,0.331345,0.477769,213960.6789,0.947333,89.58511

In [3]:
# Checking for missing values
print(train.isna().sum())
print()
print(test.isna().sum())

id                           0
RhythmScore                  0
AudioLoudness                0
VocalContent                 0
AcousticQuality              0
InstrumentalScore            0
LivePerformanceLikelihood    0
MoodScore                    0
TrackDurationMs              0
Energy                       0
BeatsPerMinute               0
dtype: int64

id                           0
RhythmScore                  0
AudioLoudness                0
VocalContent                 0
AcousticQuality              0
InstrumentalScore            0
LivePerformanceLikelihood    0
MoodScore                    0
TrackDurationMs              0
Energy                       0
dtype: int64

In [4]:
train.describe()

,id,RhythmScore,AudioLoudness,VocalContent,AcousticQuality,InstrumentalScore,LivePerformanceLikelihood,MoodScore,TrackDurationMs,Energy,BeatsPerMinute
count,524164.000000,524164.000000,524164.000000,524164.000000,524164.000000,524164.000000,524164.000000,524164.000000,524164.000000,524164.000000,524164.000000
mean,262081.500000,0.632843,-8.379014,0.074443,0.262913,0.117690,0.178398,0.555843,241903.692949,0.500923,119.034899
std,151313.257587,0.156899,4.616221,0.049939,0.223120,0.131845,0.118186,0.225480,59326.601501,0.289952,26.468077
min,0.000000,0.076900,-27.509725,0.023500,0.000005,0.000001,0.024300,0.025600,63973.000000,0.000067,46.718000
25%,131040.750000,0.515850,-11.551933,0.023500,0.069413,0.000001,0.077637,0.403921,207099.876625,0.254933,101.070410
50%,262081.500000,0.634686,-8.252499,0.066425,0.242502,0.074247,0.166327,0.564817,243684.058150,0.511800,118.747660
75%,393122.250000,0.739179,-4.912298,0.107343,0.396957,0.204065,0.268946,0.716633,281851.658500,0.746000,136.686590
max,524163.000000,0.975000,-1.357000,0.256401,0.995000,0.869258,0.599924,0.978000,464723.228100,1.000000,206.037000

In [ ]:
from torch.utils.data import TensorDataset, DataLoader, random_split, Dataset
import numpy as np

class CustomeDataSet(Dataset):
    def __init__(self, x_data, y_data):
        self.x = x_data
        self.y = y_data
        
    def __getitem__(self, index):
        return self.x[index], self.y[index]
    
    def __len__(self):
        return len(self.x)

train_dataset = train.drop(['id'], axis=1)
y_train = train_dataset['BeatsPerMinute']
x_train = train_dataset.drop(['BeatsPerMinute'], axis=1)
y_train = np.array(y_train.values.tolist(), dtype=np.float32)
x_train = np.array(x_train.values.tolist(), dtype=np.float32)

train_dataset = CustomeDataSet(x_train, y_train)
train_dataset, val_dataset = random_split(train_dataset, [0.8, 0.2],)

len(train_dataset), len(val_dataset)

(419332, 104832)

In [ ]:
import torch.nn as nn

class BaselineModel(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim=1):
        super(BaselineModel, self).__init__()
        self.network = nn.Sequential(
            nn.Linear(in_features=input_dim, out_features=hidden_dim),
            nn.Linear(in_features=hidden_dim, out_features=output_dim)
        )

    def forward(self, x):
        return self.network(x)

In [ ]:
batch_size = 64
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

In [44]:
input_dim = 9
hidden_dim = 12
output_dim = 1

learning_rate = 5e-12
epochs = 10

In [45]:
train_dataset

In [ ]:
import torch
import torch.optim as optim

model = BaselineModel(input_dim, hidden_dim, output_dim)
optimizer = optim.SGD(model.parameters(), lr=learning_rate)
criterion = nn.MSELoss()

for epoch in range(epochs):
    model.train()
    # Convert numpy array to torch Variable
    inputs = torch.from_numpy(x_train).requires_grad_()
    targets = torch.from_numpy(y_train)
    
    val_inputs = torch.from_numpy(x_val).requires_grad_()
    val_targets = torch.from_numpy(y_val)

    # Clear gradients w.r.t. parameters
    optimizer.zero_grad() 

    # Forward to get output
    outputs = baselineModel(inputs)
    val_outputs = baselineModel(val_inputs)

    # Calculate Loss
    loss = criterion(outputs, targets)
    val_loss = criterion(val_outputs, val_targets)
    
    # Getting gradients w.r.t. parameters
    loss.backward()

    # Updating parameters
    optimizer.step()

    print('epoch {}, loss {}, validation loss {}'.format(epoch, loss.item(), val_loss.item()))

epoch 1, loss 2883512832.0, validation loss 2882125056.0
epoch 2, loss 778913728.0, validation loss 778539136.0
epoch 3, loss 252352192.0, validation loss 252230928.0
epoch 4, loss 85795352.0, validation loss 85754200.0
epoch 5, loss 29624976.0, validation loss 29610812.0
epoch 6, loss 10283686.0, validation loss 10278793.0
epoch 7, loss 3576772.0, validation loss 3575086.25
epoch 8, loss 1245437.625, validation loss 1244861.75
epoch 9, loss 434389.34375, validation loss 434196.40625
epoch 10, loss 152158.125, validation loss 152096.578125
epoch 11, loss 53935.82421875, validation loss 53918.9296875
epoch 12, loss 19751.931640625, validation loss 19749.9453125
epoch 13, loss 7854.83740234375, validation loss 7857.66748046875
epoch 14, loss 3714.12060546875, validation loss 3718.407470703125
epoch 15, loss 2273.185791015625, validation loss 2277.847412109375
epoch 16, loss 1771.6971435546875, validation loss 1776.4122314453125
epoch 17, loss 1597.140380859375, validation loss 1601.82861328125
epoch 18, loss 1536.416015625, validation loss 1541.0677490234375
epoch 19, loss 1515.2802734375, validation loss 1519.9041748046875
epoch 20, loss 1507.91748046875, validation loss 1512.5224609375
epoch 21, loss 1505.354736328125, validation loss 1509.94775390625
epoch 22, loss 1504.4613037109375, validation loss 1509.0458984375
epoch 23, loss 1504.150146484375, validation loss 1508.7310791015625
epoch 24, loss 1504.0423583984375, validation loss 1508.6202392578125
epoch 25, loss 1504.0045166015625, validation loss 1508.5806884765625
epoch 26, loss 1503.9913330078125, validation loss 1508.566650390625
epoch 27, loss 1503.987060546875, validation loss 1508.5618896484375
epoch 28, loss 1503.9854736328125, validation loss 1508.559326171875
epoch 29, loss 1503.9849853515625, validation loss 1508.55908203125
epoch 30, loss 1503.9849853515625, validation loss 1508.55859375
epoch 31, loss 1503.98486328125, validation loss 1508.55859375
epoch 32, loss 1503.98486328125, validation loss 1508.55859375
epoch 33, loss 1503.98486328125, validation loss 1508.55859375
epoch 34, loss 1503.98486328125, validation loss 1508.5582275390625
epoch 35, loss 1503.984619140625, validation loss 1508.5587158203125
epoch 36, loss 1503.98486328125, validation loss 1508.55859375
epoch 37, loss 1503.984619140625, validation loss 1508.5582275390625
epoch 38, loss 1503.984619140625, validation loss 1508.5582275390625
epoch 39, loss 1503.98486328125, validation loss 1508.5582275390625
epoch 40, loss 1503.98486328125, validation loss 1508.5582275390625
epoch 41, loss 1503.984619140625, validation loss 1508.5582275390625
epoch 42, loss 1503.98486328125, validation loss 1508.55810546875
epoch 43, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 44, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 45, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 46, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 47, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 48, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 49, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 50, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 51, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 52, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 53, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 54, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 55, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 56, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 57, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 58, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 59, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 60, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 61, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 62, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 63, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 64, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 65, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 66, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 67, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 68, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 69, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 70, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 71, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 72, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 73, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 74, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 75, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 76, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 77, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 78, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 79, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 80, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 81, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 82, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 83, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 84, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 85, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 86, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 87, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 88, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 89, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 90, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 91, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 92, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 93, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 94, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 95, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 96, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 97, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 98, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 99, loss 1503.9849853515625, validation loss 1508.5582275390625
epoch 100, loss 1503.9849853515625, validation loss 1508.5582275390625

In [215]:
class MultipleLayersModel(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim=1):
        super(MultipleLayersModel, self).__init__()
        self.network = nn.Sequential(
            nn.Linear(in_features=input_dim, out_features=hidden_dim),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(in_features=hidden_dim, out_features=hidden_dim),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(in_features=hidden_dim, out_features=output_dim),
            nn.ReLU()
        )

    def forward(self, x):
        return self.network(x)

In [ ]:
input_dim = 9
hidden_dim = 128
output_dim = 1

learning_rate = 1e-3
epochs = 50

multipleLayersModel = MultipleLayersModel(input_dim, hidden_dim, output_dim)
optimizer_SGD = torch.optim.SGD(multipleLayersModel.parameters(), lr=learning_rate)
optimizer_Adam = torch.optim.Adam(multipleLayersModel.parameters(), lr=learning_rate)

criterion = nn.MSELoss()

In [217]:
for epoch in range(epochs):
    epoch += 1
    # Convert numpy array to torch Variable
    inputs = torch.from_numpy(x_train).requires_grad_()
    targets = torch.from_numpy(y_train)
    
    val_inputs = torch.from_numpy(x_val).requires_grad_()
    val_targets = torch.from_numpy(y_val)

    # Clear gradients w.r.t. parameters
    optimizer_Adam.zero_grad()

    # Forward to get output
    outputs = multipleLayersModel(inputs)
    val_outputs = multipleLayersModel(val_inputs)

    # Calculate Loss
    loss = criterion(outputs, targets)
    val_loss = criterion(val_outputs, val_targets)
    
    # Getting gradients w.r.t. parameters
    loss.backward()

    # Updating parameters
    optimizer_Adam.step()

    print('epoch {}, loss {}, validation loss {}'.format(epoch, loss.item(), val_loss.item()))

epoch 1, loss 25423.63671875, validation loss 24842.85546875
epoch 2, loss 14924.1826171875, validation loss 15015.3173828125
epoch 3, loss 14869.826171875, validation loss 14870.0166015625
epoch 4, loss 14869.826171875, validation loss 14870.0166015625
epoch 5, loss 14869.826171875, validation loss 14870.0166015625
epoch 6, loss 14869.826171875, validation loss 14870.0166015625
epoch 7, loss 14869.826171875, validation loss 14870.0166015625
epoch 8, loss 14869.826171875, validation loss 14870.0166015625
epoch 9, loss 14869.826171875, validation loss 14870.0166015625
epoch 10, loss 14869.826171875, validation loss 14870.0166015625
epoch 11, loss 14869.826171875, validation loss 14870.0166015625
epoch 12, loss 14869.826171875, validation loss 14870.0166015625
epoch 13, loss 14869.826171875, validation loss 14870.0166015625
epoch 14, loss 14869.826171875, validation loss 14870.0166015625
epoch 15, loss 14869.826171875, validation loss 14870.0166015625
epoch 16, loss 14869.826171875, validation loss 14870.0166015625
epoch 17, loss 14869.826171875, validation loss 14870.0166015625
epoch 18, loss 14869.826171875, validation loss 14870.0166015625
epoch 19, loss 14869.826171875, validation loss 14870.0166015625
epoch 20, loss 14869.826171875, validation loss 14870.0166015625
epoch 21, loss 14869.826171875, validation loss 14870.0166015625
epoch 22, loss 14869.826171875, validation loss 14870.0166015625
epoch 23, loss 14869.826171875, validation loss 14870.0166015625
epoch 24, loss 14869.826171875, validation loss 14870.0166015625

KeyboardInterrupt: