In [1]:
pip install pandas numpy matplotlib seaborn tqdm IPython pyarrow fastparquet torch

Requirement already satisfied: pandas in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (2.3.3)
Requirement already satisfied: numpy in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (2.3.3)
Requirement already satisfied: matplotlib in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (3.10.6)
Requirement already satisfied: seaborn in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (0.13.2)
Requirement already satisfied: tqdm in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (4.67.1)
Requirement already satisfied: IPython in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (9.6.0)
Requirement already satisfied: pyarrow in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (21.0.0)
Requirement already satisfied: fastparquet in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (2024.11.0)
Requirement already satisfied: torch in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (2.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: decorator in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from IPython) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from IPython) (1.1.1)
Requirement already satisfied: jedi>=0.16 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from IPython) (0.19.2)
Requirement already satisfied: matplotlib-inline in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from IPython) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from IPython) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from IPython) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from IPython) (2.19.2)
Requirement already satisfied: stack_data in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from IPython) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from IPython) (5.14.3)
Requirement already satisfied: typing_extensions>=4.6 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from IPython) (4.15.0)
Requirement already satisfied: wcwidth in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->IPython) (0.2.14)
Requirement already satisfied: cramjam>=2.3 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from fastparquet) (2.11.0)
Requirement already satisfied: fsspec in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from fastparquet) (2025.9.0)
Requirement already satisfied: filelock in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from torch) (3.20.0)
Requirement already satisfied: sympy>=1.13.3 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from torch) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from torch) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.5.0 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from torch) (3.5.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from jedi>=0.16->IPython) (0.8.5)
Requirement already satisfied: ptyprocess>=0.5 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from pexpect>4.3->IPython) (0.7.0)
Requirement already satisfied: six>=1.5 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: executing>=1.2.0 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from stack_data->IPython) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from stack_data->IPython) (3.0.0)
Requirement already satisfied: pure-eval in /home/hvtruong/Projects/Kaggle/.venv/lib/python3.11/site-packages (from stack_data->IPython) (0.2.3)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Some common libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Dataset preparation

In [3]:
# Load dataset
df = pd.read_csv('dataset/train.csv')
print(f"Initial dataset shape: {df.shape}")
display(df.head())

print("\nMissing values per column:")
print(df.isna().sum())

Initial dataset shape: (891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Missing values per column:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [4]:
def reformat_name(name):
    if ',' in name or '.' in name:
        title = name.split(', ')[1].split('. ')[0].strip()
        return f"{title}"
    return name
    
def reformat_sex(sex):
    return 1 if sex =='male' else 0

def reformat_embark(embark):
    if embark == 'S':
        return 0
    elif embark == 'C':
        return 1
    elif embark == 'Q':
        return 2

In [5]:
df['Name'] = df['Name'].apply(reformat_name)
df['Sex'] = df['Sex'].apply(reformat_sex)
df['Embarked'] = df['Embarked'].apply(reformat_embark)

In [6]:
for col in df.columns:
    num_unique_values = df[col].nunique()
    if num_unique_values / len(df) > 0.5:
        print(f"Column '{col}' has high cardinality with {num_unique_values} unique values over {len(df)} data.")

Column 'PassengerId' has high cardinality with 891 unique values over 891 data.
Column 'Ticket' has high cardinality with 681 unique values over 891 data.

In [7]:
IGNORED_COLUMNS = ['PassengerId', 'Ticket', 'Cabin']

df.drop(columns=IGNORED_COLUMNS, inplace=True, axis=1)
print(f"\nTruncated dataset shape: {df.shape}")
display(df.head(n=10))

Truncated dataset shape: (891, 9)

   Survived  Pclass    Name  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3      Mr    1  22.0      1      0   7.2500       0.0
1         1       1     Mrs    0  38.0      1      0  71.2833       1.0
2         1       3    Miss    0  26.0      0      0   7.9250       0.0
3         1       1     Mrs    0  35.0      1      0  53.1000       0.0
4         0       3      Mr    1  35.0      0      0   8.0500       0.0
5         0       3      Mr    1   NaN      0      0   8.4583       2.0
6         0       1      Mr    1  54.0      0      0  51.8625       0.0
7         0       3  Master    1   2.0      3      1  21.0750       0.0
8         1       3     Mrs    0  27.0      0      2  11.1333       0.0
9         1       2     Mrs    0  14.0      1      0  30.0708       1.0

In [8]:
# Filled dataset
for col in df.select_dtypes(include=[np.number]).columns:
    skewness = df[col].skew()
    print(f"{col} → skewness: {skewness:.2f}")
    
    if abs(skewness) < 0.5:
        fill_value = df[col].mean()
        method = "mean"
    else:
        fill_value = df[col].median()
        method = "median"
    if df[col].isnull().sum() > 0:
        df.fillna({col: fill_value}, inplace=True)
        print(f"Filled {col} using {method} ({fill_value:.2f})")

Survived → skewness: 0.48
Pclass → skewness: -0.63
Sex → skewness: -0.62
Age → skewness: 0.39
Filled Age using mean (29.70)
SibSp → skewness: 3.70
Parch → skewness: 2.75
Fare → skewness: 4.79
Embarked → skewness: 1.54
Filled Embarked using median (0.00)

In [9]:
df_encoded = pd.get_dummies(df, columns=['Pclass', 'Name', 'Sex', 'Embarked'], dtype=int, drop_first=True)
df_encoded

,Survived,Age,SibSp,Parch,Fare,Pclass_2,Pclass_3,Name_Col,Name_Don,Name_Dr,...,Name_Mme,Name_Mr,Name_Mrs,Name_Ms,Name_Rev,Name_Sir,Name_the Countess,Sex_1,Embarked_1.0,Embarked_2.0
0,0,22.000000,1,0,7.2500,0,1,0,0,0,...,0,1,0,0,0,0,0,1,0,0
1,1,38.000000,1,0,71.2833,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
2,1,26.000000,0,0,7.9250,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,35.000000,1,0,53.1000,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,0,35.000000,0,0,8.0500,0,1,0,0,0,...,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,27.000000,0,0,13.0000,1,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
887,1,19.000000,0,0,30.0000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
888,0,29.699118,1,2,23.4500,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
889,1,26.000000,0,0,30.0000,0,0,0,0,0,...,0,1,0,0,0,0,0,1,1,0
890,0,32.000000,0,0,7.7500,0,1,0,0,0,...,0,1,0,0,0,0,0,1,0,1

## Features exploration

In [10]:
for col in df.columns:
    if col == 'Survived':
        continue
    for unique_value in df[col].unique():
        if pd.isna(unique_value):
            continue
        count = df.loc[df[col] == unique_value]["Survived"]
        print(f"% of {col} {unique_value} who survived:", sum(count)/len(count))
    print("-----\n")

% of Pclass 3 who survived: 0.24236252545824846
% of Pclass 1 who survived: 0.6296296296296297
% of Pclass 2 who survived: 0.47282608695652173
-----

% of Name Mr who survived: 0.15667311411992263
% of Name Mrs who survived: 0.792
% of Name Miss who survived: 0.6978021978021978
% of Name Master who survived: 0.575
% of Name Don who survived: 0.0
% of Name Rev who survived: 0.0
% of Name Dr who survived: 0.42857142857142855
% of Name Mme who survived: 1.0
% of Name Ms who survived: 1.0
% of Name Major who survived: 0.5
% of Name Lady who survived: 1.0
% of Name Sir who survived: 1.0
% of Name Mlle who survived: 1.0
% of Name Col who survived: 0.5
% of Name Capt who survived: 0.0
% of Name the Countess who survived: 1.0
% of Name Jonkheer who survived: 0.0
-----

% of Sex 1 who survived: 0.18890814558058924
% of Sex 0 who survived: 0.7420382165605095
-----

% of Age 22.0 who survived: 0.4074074074074074
% of Age 38.0 who survived: 0.45454545454545453
% of Age 26.0 who survived: 0.3333333333333333
% of Age 35.0 who survived: 0.6111111111111112
% of Age 29.69911764705882 who survived: 0.2937853107344633
% of Age 54.0 who survived: 0.375
% of Age 2.0 who survived: 0.3
% of Age 27.0 who survived: 0.6111111111111112
% of Age 14.0 who survived: 0.5
% of Age 4.0 who survived: 0.7
% of Age 58.0 who survived: 0.6
% of Age 20.0 who survived: 0.2
% of Age 39.0 who survived: 0.35714285714285715
% of Age 55.0 who survived: 0.5
% of Age 31.0 who survived: 0.47058823529411764
% of Age 34.0 who survived: 0.4
% of Age 15.0 who survived: 0.8
% of Age 28.0 who survived: 0.28
% of Age 8.0 who survived: 0.5
% of Age 19.0 who survived: 0.36
% of Age 40.0 who survived: 0.46153846153846156
% of Age 66.0 who survived: 0.0
% of Age 42.0 who survived: 0.46153846153846156
% of Age 21.0 who survived: 0.20833333333333334
% of Age 18.0 who survived: 0.34615384615384615
% of Age 3.0 who survived: 0.8333333333333334
% of Age 7.0 who survived: 0.3333333333333333
% of Age 49.0 who survived: 0.6666666666666666
% of Age 29.0 who survived: 0.4
% of Age 65.0 who survived: 0.0
% of Age 28.5 who survived: 0.0
% of Age 5.0 who survived: 1.0
% of Age 11.0 who survived: 0.25
% of Age 45.0 who survived: 0.4166666666666667
% of Age 17.0 who survived: 0.46153846153846156
% of Age 32.0 who survived: 0.5
% of Age 16.0 who survived: 0.35294117647058826
% of Age 25.0 who survived: 0.2608695652173913
% of Age 0.83 who survived: 1.0
% of Age 30.0 who survived: 0.4
% of Age 33.0 who survived: 0.4
% of Age 23.0 who survived: 0.3333333333333333
% of Age 24.0 who survived: 0.5
% of Age 46.0 who survived: 0.0
% of Age 59.0 who survived: 0.0
% of Age 71.0 who survived: 0.0
% of Age 37.0 who survived: 0.16666666666666666
% of Age 47.0 who survived: 0.1111111111111111
% of Age 14.5 who survived: 0.0
% of Age 70.5 who survived: 0.0
% of Age 32.5 who survived: 0.5
% of Age 12.0 who survived: 1.0
% of Age 9.0 who survived: 0.25
% of Age 36.5 who survived: 0.0
% of Age 51.0 who survived: 0.2857142857142857
% of Age 55.5 who survived: 0.0
% of Age 40.5 who survived: 0.0
% of Age 44.0 who survived: 0.3333333333333333
% of Age 1.0 who survived: 0.7142857142857143
% of Age 61.0 who survived: 0.0
% of Age 56.0 who survived: 0.5
% of Age 50.0 who survived: 0.5
% of Age 36.0 who survived: 0.5
% of Age 45.5 who survived: 0.0
% of Age 20.5 who survived: 0.0
% of Age 62.0 who survived: 0.5
% of Age 41.0 who survived: 0.3333333333333333
% of Age 52.0 who survived: 0.5
% of Age 63.0 who survived: 1.0
% of Age 23.5 who survived: 0.0
% of Age 0.92 who survived: 1.0
% of Age 43.0 who survived: 0.2
% of Age 60.0 who survived: 0.5
% of Age 10.0 who survived: 0.0
% of Age 64.0 who survived: 0.0
% of Age 13.0 who survived: 1.0
% of Age 48.0 who survived: 0.6666666666666666
% of Age 0.75 who survived: 1.0
% of Age 53.0 who survived: 1.0
% of Age 57.0 who survived: 0.0
% of Age 80.0 who survived: 1.0
% of Age 70.0 who survived: 0.0
% of Age 24.5 who survived: 0.0
% of Age 6.0 who survived: 0.6666666666666666
% of Age 0.67 who survived: 1.0
% of Age 30.5 who survived: 0.0
% of Age 0.42 who survived: 1.0
% of Age 34.5 who survived: 0.0
% of Age 74.0 who survived: 0.0
-----

% of SibSp 1 who survived: 0.5358851674641149
% of SibSp 0 who survived: 0.34539473684210525
% of SibSp 3 who survived: 0.25
% of SibSp 4 who survived: 0.16666666666666666
% of SibSp 2 who survived: 0.4642857142857143
% of SibSp 5 who survived: 0.0
% of SibSp 8 who survived: 0.0
-----

% of Parch 0 who survived: 0.34365781710914456
% of Parch 1 who survived: 0.5508474576271186
% of Parch 2 who survived: 0.5
% of Parch 5 who survived: 0.2
% of Parch 3 who survived: 0.6
% of Parch 4 who survived: 0.0
% of Parch 6 who survived: 0.0
-----

% of Fare 7.25 who survived: 0.07692307692307693
% of Fare 71.2833 who survived: 1.0
% of Fare 7.925 who survived: 0.4444444444444444
% of Fare 53.1 who survived: 0.6
% of Fare 8.05 who survived: 0.11627906976744186
% of Fare 8.4583 who survived: 0.0
% of Fare 51.8625 who survived: 0.5
% of Fare 21.075 who survived: 0.0
% of Fare 11.1333 who survived: 1.0
% of Fare 30.0708 who survived: 0.5
% of Fare 16.7 who survived: 1.0
% of Fare 26.55 who survived: 0.5333333333333333
% of Fare 31.275 who survived: 0.0
% of Fare 7.8542 who survived: 0.23076923076923078
% of Fare 16.0 who survived: 1.0
% of Fare 29.125 who survived: 0.0
% of Fare 13.0 who survived: 0.38095238095238093
% of Fare 18.0 who survived: 0.0
% of Fare 7.225 who survived: 0.25
% of Fare 26.0 who survived: 0.4838709677419355
% of Fare 8.0292 who survived: 1.0
% of Fare 35.5 who survived: 0.75
% of Fare 31.3875 who survived: 0.75
% of Fare 263.0 who survived: 0.5
% of Fare 7.8792 who survived: 1.0
% of Fare 7.8958 who survived: 0.02631578947368421
% of Fare 27.7208 who survived: 0.2
% of Fare 146.5208 who survived: 1.0
% of Fare 7.75 who survived: 0.35294117647058826
% of Fare 10.5 who survived: 0.375
% of Fare 82.1708 who survived: 0.5
% of Fare 52.0 who survived: 0.42857142857142855
% of Fare 7.2292 who survived: 0.26666666666666666
% of Fare 11.2417 who survived: 1.0
% of Fare 9.475 who survived: 0.0
% of Fare 21.0 who survived: 0.3333333333333333
% of Fare 41.5792 who survived: 0.6666666666666666
% of Fare 15.5 who survived: 0.375
% of Fare 21.6792 who survived: 0.0
% of Fare 17.8 who survived: 0.0
% of Fare 39.6875 who survived: 0.0
% of Fare 7.8 who survived: 0.0
% of Fare 76.7292 who survived: 1.0
% of Fare 61.9792 who survived: 0.0
% of Fare 27.75 who survived: 0.5
% of Fare 46.9 who survived: 0.0
% of Fare 80.0 who survived: 1.0
% of Fare 83.475 who survived: 0.5
% of Fare 27.9 who survived: 0.0
% of Fare 15.2458 who survived: 0.6
% of Fare 8.1583 who survived: 0.0
% of Fare 8.6625 who survived: 0.07692307692307693
% of Fare 73.5 who survived: 0.0
% of Fare 14.4542 who survived: 0.14285714285714285
% of Fare 56.4958 who survived: 0.7142857142857143
% of Fare 7.65 who survived: 0.25
% of Fare 29.0 who survived: 1.0
% of Fare 12.475 who survived: 1.0
% of Fare 9.0 who survived: 0.0
% of Fare 9.5 who survived: 0.2222222222222222
% of Fare 7.7875 who survived: 1.0
% of Fare 47.1 who survived: 0.0
% of Fare 15.85 who survived: 0.5
% of Fare 34.375 who survived: 0.0
% of Fare 61.175 who survived: 0.0
% of Fare 20.575 who survived: 0.5
% of Fare 34.6542 who survived: 0.0
% of Fare 63.3583 who survived: 1.0
% of Fare 23.0 who survived: 1.0
% of Fare 77.2875 who survived: 0.0
% of Fare 8.6542 who survived: 0.0
% of Fare 7.775 who survived: 0.1875
% of Fare 24.15 who survived: 0.125
% of Fare 9.825 who survived: 0.0
% of Fare 14.4583 who survived: 0.0
% of Fare 247.5208 who survived: 0.5
% of Fare 7.1417 who survived: 1.0
% of Fare 22.3583 who survived: 1.0
% of Fare 6.975 who survived: 0.5
% of Fare 7.05 who survived: 0.0
% of Fare 14.5 who survived: 0.2857142857142857
% of Fare 15.0458 who survived: 0.0
% of Fare 26.2833 who survived: 1.0
% of Fare 9.2167 who survived: 0.0
% of Fare 79.2 who survived: 0.5
% of Fare 6.75 who survived: 0.0
% of Fare 11.5 who survived: 0.0
% of Fare 36.75 who survived: 0.5
% of Fare 7.7958 who survived: 0.3333333333333333
% of Fare 12.525 who survived: 0.0
% of Fare 66.6 who survived: 0.5
% of Fare 7.3125 who survived: 0.0
% of Fare 61.3792 who survived: 0.0
% of Fare 7.7333 who survived: 0.5
% of Fare 69.55 who survived: 0.0
% of Fare 16.1 who survived: 0.2222222222222222
% of Fare 15.75 who survived: 1.0
% of Fare 20.525 who survived: 0.6666666666666666
% of Fare 55.0 who survived: 1.0
% of Fare 25.925 who survived: 0.0
% of Fare 33.5 who survived: 0.0
% of Fare 30.6958 who survived: 0.0
% of Fare 25.4667 who survived: 0.0
% of Fare 28.7125 who survived: 0.0
% of Fare 0.0 who survived: 0.06666666666666667
% of Fare 15.05 who survived: 0.0
% of Fare 39.0 who survived: 0.75
% of Fare 22.025 who survived: 1.0
% of Fare 50.0 who survived: 0.0
% of Fare 8.4042 who survived: 0.0
% of Fare 6.4958 who survived: 0.0
% of Fare 10.4625 who survived: 0.0
% of Fare 18.7875 who survived: 0.5
% of Fare 31.0 who survived: 0.6666666666666666
% of Fare 113.275 who survived: 0.6666666666666666
% of Fare 27.0 who survived: 0.5
% of Fare 76.2917 who survived: 1.0
% of Fare 90.0 who survived: 0.75
% of Fare 9.35 who survived: 0.5
% of Fare 13.5 who survived: 0.25
% of Fare 7.55 who survived: 0.25
% of Fare 26.25 who survived: 0.6666666666666666
% of Fare 12.275 who survived: 0.0
% of Fare 7.125 who survived: 0.0
% of Fare 52.5542 who survived: 1.0
% of Fare 20.2125 who survived: 0.0
% of Fare 86.5 who survived: 1.0
% of Fare 512.3292 who survived: 1.0
% of Fare 79.65 who survived: 0.6666666666666666
% of Fare 153.4625 who survived: 0.6666666666666666
% of Fare 135.6333 who survived: 0.6666666666666666
% of Fare 19.5 who survived: 1.0
% of Fare 29.7 who survived: 0.3333333333333333
% of Fare 77.9583 who survived: 1.0
% of Fare 20.25 who survived: 0.5
% of Fare 78.85 who survived: 0.5
% of Fare 91.0792 who survived: 1.0
% of Fare 12.875 who survived: 0.0
% of Fare 8.85 who survived: 0.0
% of Fare 151.55 who survived: 0.5
% of Fare 30.5 who survived: 0.8
% of Fare 23.25 who survived: 1.0
% of Fare 12.35 who survived: 0.6666666666666666
% of Fare 110.8833 who survived: 0.75
% of Fare 108.9 who survived: 0.5
% of Fare 24.0 who survived: 0.5
% of Fare 56.9292 who survived: 1.0
% of Fare 83.1583 who survived: 1.0
% of Fare 262.375 who survived: 1.0
% of Fare 14.0 who survived: 0.0
% of Fare 164.8667 who survived: 1.0
% of Fare 134.5 who survived: 1.0
% of Fare 6.2375 who survived: 0.0
% of Fare 57.9792 who survived: 1.0
% of Fare 28.5 who survived: 0.0
% of Fare 133.65 who survived: 1.0
% of Fare 15.9 who survived: 1.0
% of Fare 9.225 who survived: 0.0
% of Fare 35.0 who survived: 0.0
% of Fare 75.25 who survived: 1.0
% of Fare 69.3 who survived: 1.0
% of Fare 55.4417 who survived: 1.0
% of Fare 211.5 who survived: 0.0
% of Fare 4.0125 who survived: 0.0
% of Fare 227.525 who survived: 0.75
% of Fare 15.7417 who survived: 1.0
% of Fare 7.7292 who survived: 0.0
% of Fare 12.0 who survived: 1.0
% of Fare 120.0 who survived: 1.0
% of Fare 12.65 who survived: 1.0
% of Fare 18.75 who survived: 1.0
% of Fare 6.8583 who survived: 0.0
% of Fare 32.5 who survived: 1.0
% of Fare 7.875 who survived: 0.0
% of Fare 14.4 who survived: 0.0
% of Fare 55.9 who survived: 0.5
% of Fare 8.1125 who survived: 1.0
% of Fare 81.8583 who survived: 1.0
% of Fare 19.2583 who survived: 1.0
% of Fare 19.9667 who survived: 0.0
% of Fare 89.1042 who survived: 1.0
% of Fare 38.5 who survived: 0.0
% of Fare 7.725 who survived: 0.0
% of Fare 13.7917 who survived: 1.0
% of Fare 9.8375 who survived: 0.0
% of Fare 7.0458 who survived: 0.0
% of Fare 7.5208 who survived: 0.0
% of Fare 12.2875 who survived: 1.0
% of Fare 9.5875 who survived: 0.5
% of Fare 49.5042 who survived: 0.5
% of Fare 78.2667 who survived: 1.0
% of Fare 15.1 who survived: 0.0
% of Fare 7.6292 who survived: 0.0
% of Fare 22.525 who survived: 0.0
% of Fare 26.2875 who survived: 1.0
% of Fare 59.4 who survived: 1.0
% of Fare 7.4958 who survived: 0.3333333333333333
% of Fare 34.0208 who survived: 0.0
% of Fare 93.5 who survived: 1.0
% of Fare 221.7792 who survived: 0.0
% of Fare 106.425 who survived: 0.5
% of Fare 49.5 who survived: 1.0
% of Fare 71.0 who survived: 0.5
% of Fare 13.8625 who survived: 1.0
% of Fare 7.8292 who survived: 0.5
% of Fare 39.6 who survived: 0.5
% of Fare 17.4 who survived: 1.0
% of Fare 51.4792 who survived: 1.0
% of Fare 26.3875 who survived: 1.0
% of Fare 30.0 who survived: 0.8333333333333334
% of Fare 40.125 who survived: 0.0
% of Fare 8.7125 who survived: 0.0
% of Fare 15.0 who survived: 0.0
% of Fare 33.0 who survived: 0.6666666666666666
% of Fare 42.4 who survived: 0.0
% of Fare 15.55 who survived: 0.0
% of Fare 65.0 who survived: 1.0
% of Fare 32.3208 who survived: 0.0
% of Fare 7.0542 who survived: 0.0
% of Fare 8.4333 who survived: 0.0
% of Fare 25.5875 who survived: 0.0
% of Fare 9.8417 who survived: 1.0
% of Fare 8.1375 who survived: 0.0
% of Fare 10.1708 who survived: 0.0
% of Fare 211.3375 who survived: 1.0
% of Fare 57.0 who survived: 1.0
% of Fare 13.4167 who survived: 1.0
% of Fare 7.7417 who survived: 0.0
% of Fare 9.4833 who survived: 0.0
% of Fare 7.7375 who survived: 0.5
% of Fare 8.3625 who survived: 0.0
% of Fare 23.45 who survived: 0.0
% of Fare 25.9292 who survived: 1.0
% of Fare 8.6833 who survived: 1.0
% of Fare 8.5167 who survived: 1.0
% of Fare 7.8875 who survived: 0.0
% of Fare 37.0042 who survived: 0.5
% of Fare 6.45 who survived: 0.0
% of Fare 6.95 who survived: 0.0
% of Fare 8.3 who survived: 0.0
% of Fare 6.4375 who survived: 0.0
% of Fare 39.4 who survived: 1.0
% of Fare 14.1083 who survived: 0.0
% of Fare 13.8583 who survived: 1.0
% of Fare 50.4958 who survived: 0.0
% of Fare 5.0 who survived: 0.0
% of Fare 9.8458 who survived: 0.0
% of Fare 10.5167 who survived: 0.0
-----

% of Embarked 0.0 who survived: 0.33900928792569657
% of Embarked 1.0 who survived: 0.5535714285714286
% of Embarked 2.0 who survived: 0.38961038961038963
-----

## Data loaders

In [11]:
import torch
from torch.utils.data import DataLoader, TensorDataset

class DataSet(torch.utils.data.Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y
    
    def __len__(self):
        return len(self.y)
    
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]
    
dataset = TensorDataset(
    torch.tensor(df_encoded.drop(columns=['Survived']).values),
    torch.tensor(df_encoded['Survived'].values)
)
# Create DataLoader
dataloader = DataLoader(
    dataset,
    batch_size=16,
    shuffle=True,
    num_workers=2
)

In [12]:
# Retrieve and print a single random batch
X, y = next(iter(dataloader))
print("Data shape:", X.shape)
print("Labels:", y)

Data shape: torch.Size([16, 25])
Labels: tensor([0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0])

In [13]:
for batch_idx, (data, target) in enumerate(dataloader):
    print(f"Batch {batch_idx+1}")
    print(f"  Data shape: {data.shape}")     # Expect [batch_size, 10]
    print(f"  Target shape: {target.shape}") # Expect [batch_size]
    print(f"  Data type: {data}")
    print(f"  Target type: {target}")
    
    # Break after first batch for quick test
    break

Batch 1
  Data shape: torch.Size([16, 25])
  Target shape: torch.Size([16])
  Data type: tensor([[50.0000,  0.0000,  0.0000, 10.5000,  1.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  1.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000],
        [42.0000,  0.0000,  0.0000, 13.0000,  1.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  1.0000,  0.0000,  0.0000,  1.0000,  0.0000,
          0.0000],
        [25.0000,  0.0000,  0.0000,  7.7417,  0.0000,  1.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          1.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  1.0000,  0.0000,
          1.0000],
        [17.0000,  0.0000,  0.0000, 10.5000,  1.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  1.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000],
        [21.0000,  0.0000,  0.0000, 77.9583,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  1.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000],
        [38.0000,  0.0000,  0.0000,  8.6625,  0.0000,  1.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          1.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  1.0000,  0.0000,
          0.0000],
        [19.0000,  0.0000,  0.0000,  7.8958,  0.0000,  1.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          1.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  1.0000,  0.0000,
          0.0000],
        [21.0000,  0.0000,  0.0000,  8.0500,  0.0000,  1.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          1.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  1.0000,  0.0000,
          0.0000],
        [28.0000,  0.0000,  0.0000,  9.5000,  0.0000,  1.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          1.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  1.0000,  0.0000,
          0.0000],
        [19.0000,  0.0000,  0.0000, 26.0000,  1.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  1.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000],
        [29.6991,  0.0000,  0.0000,  7.8958,  0.0000,  1.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          1.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  1.0000,  0.0000,
          0.0000],
        [36.0000,  0.0000,  2.0000, 71.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  1.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000],
        [25.0000,  1.0000,  2.0000, 41.5792,  1.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          1.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  1.0000,  1.0000,
          0.0000],
        [51.0000,  1.0000,  0.0000, 77.9583,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  1.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000],
        [24.0000,  0.0000,  0.0000, 69.3000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  1.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  1.0000,
          0.0000],
        [30.0000,  0.0000,  0.0000, 31.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  1.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  1.0000,
          0.0000]], dtype=torch.float64)
  Target type: tensor([1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1])

## Model experiments

### Random Forest

### KNN

### NN

## Training

In [14]:
import torch.nn as nn
import torch.optim as optim

class Trainer:
    def __init__(self, model, optimizer, criterion,  lr=1e-3):
        self.model = model
        self.optimizer = optimizer(self.model.parameters(), lr=lr)
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    def train_one_epoch(self):
        self.model.train()
        running_loss = 0.0
        for batch in self.train_loader:
            inputs, labels = [bat.to(self.device) for bat in batch]
            self.optimizer.zero_grad()
            
            outputs = self.model(inputs)
            loss = self.criterion(outputs, labels)
            loss.backward()
            self.optimizer.step()
            
            running_loss += loss.item()
        epoch_loss = running_loss / len(self.train_loader)
        return epoch_loss

    def evaluate(self):
        train_score = self.model.score(self.X_train, self.y_train)
        val_score = self.model.score(self.X_val, self.y_val)
        print(f"Train Score: {train_score:.4f}")
        print(f"Validation Score: {val_score:.4f}")